# Generated by Django 4.2.11 on 2024-04-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('countrycode', models.CharField(max_length=255)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.IntegerField()),
                ('languages', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
            ],
        ),
    ]
